# Generated by Django 5.0.4 on 2024-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('package', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('upcoming_trip_date', models.DateField()),
            ],
        ),
    ]
