# Generated by Django 5.0.4 on 2024-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhorizon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('boarding', models.CharField(max_length=200)),
                ('contactm', models.CharField(max_length=15)),
                ('contacte', models.EmailField(max_length=254)),
            ],
        ),
    ]
